browser=chrome
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
username=testuser
password=password123
DataSheet_QA=src/main/resources/MasterData.xlsx
url_qa=https://the-internet.herokuapp.com/broken_images